name: AI Debate Request
description: Request a Multi-AI debate on a technical decision
title: "[Debate] "
labels: ["ai-debate"]
body:
  - type: markdown
    attributes:
      value: |
        ## Multi-AI Debate Request

        This form will trigger a collaborative debate between Claude, Gemini, and optionally Perplexity to help make a technical decision.

        The debate will:
        - Generate multiple perspectives on your question
        - Calculate consensus scores
        - Automatically log results to docs/brain/
        - Sync to Vertex AI knowledge base

  - type: input
    id: topic
    attributes:
      label: Debate Topic
      description: What technical decision or question should the AIs debate?
      placeholder: "e.g., What's the best approach for RTL multiplication optimization?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide background information, constraints, or requirements
      placeholder: |
        - Current implementation details
        - Performance requirements
        - Known limitations
        - Other relevant context
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Being Considered
      description: List the options you're considering (if known)
      placeholder: |
        1. Option A - Description
        2. Option B - Description
        3. Option C - Description
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this decision?
      options:
        - Low - Nice to have
        - Medium - Should decide soon
        - High - Urgent decision
    default: 1

  - type: checkboxes
    id: expert_mode
    attributes:
      label: Expert Mode
      description: Options for debate conduct
      options:
        - label: Enable expert mode (include Perplexity from start)
          required: false
        - label: Quick debate (max 2 rounds)
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might help the AIs
      placeholder: Links, references, previous discussions, etc.
    validations:
      required: false
