name: Knowledge Query
description: Search the Vertex AI knowledge base for past decisions and context
title: "[Query] "
labels: ["knowledge-query"]
body:
  - type: markdown
    attributes:
      value: |
        ## Knowledge Base Query

        This form helps you search through the Vertex AI knowledge base (BigQuery + GCS) for past decisions, debates, and context.

        Note: This is for searching existing knowledge. For new decisions, use "AI Debate Request" instead.

  - type: input
    id: query
    attributes:
      label: Search Query
      description: What are you looking for?
      placeholder: "e.g., NoiseComputer multiplication rules"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide more details about what you're trying to find
      placeholder: |
        - Specific topics or keywords
        - Approximate timeframe
        - Related projects or components
    validations:
      required: false

  - type: dropdown
    id: search_scope
    attributes:
      label: Search Scope
      description: Where should we search?
      options:
        - All sources (BigQuery + GCS + GitHub)
        - BigQuery embeddings only
        - GCS decisions only
        - GitHub docs/brain/ only
    default: 0

  - type: checkboxes
    id: options
    attributes:
      label: Search Options
      options:
        - label: Include similar/related results
          required: false
        - label: Search historical debate transcripts
          required: false
        - label: Include implementation notes
          required: false
